import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          柔<br />術<br /> 33 Jiu Jitsu
        </h1>
        <h2>(Brazilian Jiu Jitsu)</h2>
        <p className={styles.description}>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque
          corrupti aliquam quidem animi, sed quo magnam maiores repudiandae
          accusantium, aspernatur doloribus fugiat iusto ducimus pariatur
          numquam, eveniet illum excepturi vitae.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
